
package org.teiid.stateservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6-patch-01
 * Wed Jan 19 13:44:29 EST 2011
 * Generated source version: 2.2.6-patch-01
 * 
 */

@WebFault(name = "GetStateInfoFault", targetNamespace = "http://www.teiid.org/stateService/")
public class GetStateInfoFault_Exception extends Exception {
    public static final long serialVersionUID = 20110119134429L;
    
    private org.teiid.stateservice.GetStateInfoFault getStateInfoFault;

    public GetStateInfoFault_Exception() {
        super();
    }
    
    public GetStateInfoFault_Exception(String message) {
        super(message);
    }
    
    public GetStateInfoFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GetStateInfoFault_Exception(String message, org.teiid.stateservice.GetStateInfoFault getStateInfoFault) {
        super(message);
        this.getStateInfoFault = getStateInfoFault;
    }

    public GetStateInfoFault_Exception(String message, org.teiid.stateservice.GetStateInfoFault getStateInfoFault, Throwable cause) {
        super(message, cause);
        this.getStateInfoFault = getStateInfoFault;
    }

    public org.teiid.stateservice.GetStateInfoFault getFaultInfo() {
        return this.getStateInfoFault;
    }
}
