
/*
 * 
 */

package org.teiid.stateservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6-patch-01
 * Wed Jan 19 13:44:29 EST 2011
 * Generated source version: 2.2.6-patch-01
 * 
 */


@WebServiceClient(name = "stateService", 
                  wsdlLocation = "file:/NotBackedUp/jdoyle/jbds.h36/ws/StateService/WebContent/stateService.wsdl",
                  targetNamespace = "http://www.teiid.org/stateService/") 
public class StateService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.teiid.org/stateService/", "stateService");
    public final static QName StateServiceSOAP = new QName("http://www.teiid.org/stateService/", "stateServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/NotBackedUp/jdoyle/jbds.h36/ws/StateService/WebContent/stateService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/NotBackedUp/jdoyle/jbds.h36/ws/StateService/WebContent/stateService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public StateService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StateService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StateService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns StateService
     */
    @WebEndpoint(name = "stateServiceSOAP")
    public StateService getStateServiceSOAP() {
        return super.getPort(StateServiceSOAP, StateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StateService
     */
    @WebEndpoint(name = "stateServiceSOAP")
    public StateService getStateServiceSOAP(WebServiceFeature... features) {
        return super.getPort(StateServiceSOAP, StateService.class, features);
    }

}
