package org.teiid.stateservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T17:38:33.432Z
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.teiid.org/stateService/", name = "stateService")
@XmlSeeAlso({ObjectFactory.class})
public interface StateService {

    @WebResult(name = "AllStateInfo", targetNamespace = "")
    @RequestWrapper(localName = "GetAllStateInfo", targetNamespace = "http://www.teiid.org/stateService/", className = "org.teiid.stateservice.GetAllStateInfo")
    @WebMethod(operationName = "GetAllStateInfo", action = "http://www.teiid.org/stateService/GetStateInfo")
    @ResponseWrapper(localName = "GetAllStateInfoResponse", targetNamespace = "http://www.teiid.org/stateService/", className = "org.teiid.stateservice.GetAllStateInfoResponse")
    public java.util.List<org.teiid.stateservice.StateInfo> getAllStateInfo();

    @WebResult(name = "StateInfo", targetNamespace = "")
    @RequestWrapper(localName = "GetStateInfo", targetNamespace = "http://www.teiid.org/stateService/", className = "org.teiid.stateservice.GetStateInfo")
    @WebMethod(operationName = "GetStateInfo", action = "http://www.teiid.org/stateService/GetStateInfo")
    @ResponseWrapper(localName = "GetStateInfoResponse", targetNamespace = "http://www.teiid.org/stateService/", className = "org.teiid.stateservice.GetStateInfoResponse")
    public org.teiid.stateservice.StateInfo getStateInfo(
        @WebParam(name = "stateCode", targetNamespace = "")
        java.lang.String stateCode
    ) throws GetStateInfoFault_Exception;
}
