#!/bin/bash

wsconsume -v -o build/classes WebContent/stateService.wsdl

PACKAGE="org/teiid/stateservice"

## mv files we want to keep into new src output
mv src/$PACKAGE/StateData.java $PACKAGE/
mv src/$PACKAGE/StateServiceImpl.java $PACKAGE/

## destroy old source
rm -rf src/org

## mv new source to correct location
mv $PACKAGE/GetStateInfoFaultException.java $PACKAGE/GetStateInfoFault_Exception.java
mv org src/
